# Generated by Django 5.2b1 on 2025-05-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gymsession",
            options={"ordering": ["-entry_time"]},
        ),
    ]
