# Generated by Django 5.2.1 on 2025-05-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_remove_member_groups_remove_member_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
